version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: retroapi
      POSTGRES_DB: retroapi
    ports:
      - "5432:5432"
  auth-server:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    ports:
      - '8010:8080'
    command: start-dev