services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: retroapi
      POSTGRES_DB: retroapi
    ports:
      - "5432:5432"
  auth-server:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    ports:
      - '8010:8080'
    command: start-dev
  rabbitmq:
    build: 
      context: ./
      dockerfile: RabbitMqDockerfile
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
      - '1883:1883'
      - '15692:15692'
      - '25672:25672'